"""add contractor id and developer id columns to jobs table

Revision ID: 00a7645d5442
Revises: 426a0684b16a
Create Date: 2021-10-12 11:33:52.189215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00a7645d5442'
down_revision = '426a0684b16a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('contractor_id', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('developer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'jobs', 'developers', ['developer_id'], ['id'])
    op.create_foreign_key(None, 'jobs', 'contractors', ['contractor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'developer_id')
    op.drop_column('jobs', 'contractor_id')
    # ### end Alembic commands ###
