"""remove password_hash column from jobs

Revision ID: 426a0684b16a
Revises: 8d0acf2651ed
Create Date: 2021-10-11 15:54:13.307691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '426a0684b16a'
down_revision = '8d0acf2651ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
